### ISSUE TITLE
Doesn't work with Jest

### ISSUE THREAD

**Issue by LoickMunoz** [se-panfilov/jsvat#77]
Error if jsvat is used with Jest during test.
(Works fine elsewhere)
```
Details:

    C:\Projets\bp-client\node_modules\jsvat\dist\index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export { austria } from './lib/countries/austria';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token export
```

jsvat : 2.0.1

**Comment by se-panfilov** [comment]
@LoickMunoz HI, thank you for using jsvat =)

Well, It should work. Maybe it because of your globally-installed jest.
Because this error occurs when jest doesn't recognise es6 import/export.
But for this purpose I added `.babelrc` to the root of the project.

In version `2.1.0` I forced it to use local version of jest. You can update and try now.
Please let me know about result

**Comment by LoickMunoz** [comment]
With the latest version it works. Thank you and good job !
